#server:
 # address: 0.0.0.0
 # port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-batch?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ibiz1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

      ddl-auto=none:show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type:
          binder:
            log: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ibizguni@gmail.com  # 실제 Gmail 주소로 대체
    password: mlcy mgxo wiop advc  # 실제 Gmail 비밀번호 또는 앱 비밀번호로 대체
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        SQL: debug
        type: trace

      springframework:
        security=DEBUG:com.example.drugtrack.controller: INFO

app:
  jwtSecret: "S29oZ3lMcHpBbnRnVW1KbXhZNHJlNzFPdk1KTjdTdXZaZmpySzZhS3Z3RHB6WFlvMFFqY3lCd2RhQ1hwYW5MY0t4QkN4L1lvZFlr"
  jwtExpirationMs: 1200




