server:

 port: 8080 # Application will run on port 8080

spring:

  jackson:
    time-zone: Asia/Seoul  # Set default time zone
  servlet:
    multipart:
      enabled: true
      max-file-size: 60MB  # Maximum file size allowed per upload
      max-request-size: 60MB  # Maximum total request size (all files combined)
  batch:
    jdbc:
      initialize-schema: never  # Prevent batch job schema initialization
    job:
      enabled: false  # Disable batch jobs from running automatically on startup
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb  # JWT signing secret (move to environment variable for security)

# database setting
  datasource:
    url: #DB URL
    username: #DB ID
    password: #DB PW
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true  # Enable SQL logging
    hibernate:
      ddl-auto: update  # Automatically update the database schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL dialect for Hibernate
        format_sql: true  # Pretty-print SQL
        use_sql_comments: true  # Add comments to SQL
        highlight_sql: true  # Highlight SQL for easier debugging
        type: trace  # Log SQL parameter values
        binder:
          log: true  # En# mail service setting - 관리자페이지의 비밀번호 초기화 기능 관련 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username:  # 실제 Gmail 주소로 대체
    password:  # 실제 Gmail 비밀번호 또는 앱 비밀번호로 대체
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.security: ERROR  # Enable detailed security logging
    org.springframework.security.web.access.ExceptionTranslationFilter: ERROR
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: ERROR
    org:
      hibernate:
        SQL: ERROR   # Enable SQL query logging
        type: ERROR
        type.descriptor.sql: ERROR
        type.descriptor.sql.BasicBinder: ERROR  # Log parameter values for SQL queries
    com.example.drugtrack.controller: ERROR  # Controller-level logging


# 공공 API 관련 설정
api:
  url: https://apis.data.go.kr/1471000/DrugPrdtPrmsnInfoService06/getDrugPrdtPrmsnDtlInq05
  serviceKey: #API KEY 입력
  type: json  # The response type expected from the public API

scheduling:
  enabled: false  # Disable scheduling by default
