name: Build and Deploy to AWS

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Gradlew 파일에 실행 권한 추가
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # 3. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # 4. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build Docker image
        run: docker build -t guni976/drug-track .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push guni976/drug-track

      # 6. AWS 인스턴스에 SSH 접속 및 Docker 업데이트
      - name: SSH to AWS and update Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          key-passphrase: ""  # 패스프레이즈가 없으면 빈 값으로 설정
          script: |
            cd /path/to/docker-compose-directory  # AWS 인스턴스에서 Docker Compose 파일이 있는 디렉토리
            docker-compose pull
            docker-compose up -d
            docker system prune -a --volumes -f
